/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
	interface RouteList {
		appearance: [];
		dashboard: [];
		home: [];
		login: [];
		logout: [];
		'password.confirm': [];
		'password.edit': [];
		'password.email': [];
		'password.request': [];
		'password.reset': [
			{
				name: 'token';
				required: true;
			},
		];
		'password.store': [];
		'password.update': [];
		'profile.destroy': [];
		'profile.edit': [];
		'profile.update': [];
		register: [];
		'storage.local': [
			{
				name: 'path';
				required: true;
			},
		];
		'verification.notice': [];
		'verification.send': [];
		'verification.verify': [
			{
				name: 'id';
				required: true;
			},
			{
				name: 'hash';
				required: true;
			},
		];
	}
}
export {};
